### ISSUE TITLE
There's a distinction between knowing how to disclose a claim as a mechanical process and full understanding the semantics of a claim

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#17]
Per the discussion on the 2-Nov-21 DIF JWP call, we need clearer language than "understood".  

_Originally posted by @selfissued in https://github.com/json-web-proofs/json-web-proofs/pull/16#discussion_r741375561_

**Comment by quartzjer** [comment]
We will definitely need exacting language here.

While there is expected to be an informed consent process with the (or _a_) subject for the contained claims, we can probably agree that it's not feasible to try and make that a requirement here.  (I'd still like to have some non-normative text or `SHOULD`s along these lines though if we can work it in)

The *bare* mechanical process of which claims are disclosed is essentially built in by just choosing which payloads to include whether its known which claim they are for or not, this is essentially just a basic JWP though.  The mapping for which claim is which payload is defined in the layout.  My position is that all payloads MUST have an associated claim mapping in that layout.  There should NOT be any payloads included in a JPT that aren't accessible as a claim.

The second mechanical process would be simply the association from a claim name in the layout to the given payload for its value.  I think the crux of this issue is here, is there use-cases where the application may not semantically understand the claim name but would still want to disclose it?

My instinct is that that situation doesn't make sense, that without knowing what the claim is, what reason would there be to include it?  My logic is circular though: if the application has a requirement to include the claim, that _is_ a semantic understanding of it.

I can imagine one intermediate case where a claim is some unknown descendent key/value of a known parent structure.  There's only a limited semantic understanding here - it's "a property of a known structure" but is still unknown itself.  Perhaps the issuer is maximizing flexibility by allowing lots of detailed disclosure, but the disclosing application is very simple and only supports a high level.  The disclosing application still knows those properties are descendants of known understood ones, so I would suggest that qualifies as a semantic understanding requirement.

Is there other use-cases? Or perhaps I'm just extolling my understanding of the word "semantics" in this context :)

**Comment by OR13** [comment]
> My position is that all payloads MUST have an associated claim mapping in that layout. There should NOT be any payloads included in a JPT that aren't accessible as a claim.

yes, this is a good idea.

> I think the crux of this issue is here, is there use-cases where the application may not semantically understand the claim name but would still want to disclose it?

Yes, that is a thing... consider getting some json, and passing it along without alteration... you might only understand half the claims in it... you don't remove claims you don't understand.

> if the application has a requirement to include the claim, that is a semantic understanding of it.

Yes, this get to the intention of the issuer... if they signed it... don't mess with it.

At a minimum, `lyt` introduces an extra burden on the issuer... they can't just "sign json" that have to define a layout for it.

This burden can be reduced with reasonable defaults.

1. There exists a default layout that can be deterministically generated from any JSON. (its a function of key value transforms, aka json pointer dictionaries). 
2. The intention of the issuer supersedes the intention of the holder w.r.t. semantics.

The issuer is defining the language, in order to use their proofs, everyone has to agree they are the boss.

This means if the issuer wants to be pedantic, they will force other folks to comprehend that stuff... don't fight the issuer on this, its their choice to express claims however they like.

Instead of trying to design around the natural tendency to over engineer semantics, just let the market find the right solution.

I think there should be an implied semantics that is built into the specification for layout, that aligns with existing understandings of "private claims"... https://datatracker.ietf.org/doc/html/rfc7519#section-4.3

An issuer does not need to "register a lyt" to use private claims... they are registering it by signing with it.

If the `lyt` does not provide enough information for the claims to be "understood" there are better solutions to that, and `lyt` should not attempt to invent semantic language features that can be found in existing languages...

I am generally nervous about `lyt` doing any "creative inventing"... it should be limited to only the structure needed to convert between a proof structure and a json representation... how that json is "understood" should be out of scope... but clearly how to use the layout MUST be understood and should be "in scope".

**Comment by quartzjer** [comment]
Since the more complex `lyt` has been replaced by the simple flat `claims` array, I believe the semantics are much much easier for applications to understand here.

While the value of a given claim might be a rich JSON object payload, the application only has to understand the unique name of that claim enough to either provide consent/disclosure choices or minimally just provide transparency about what is included.

I'm still a fan of there being a SHOULD recognize all of the claim names, but leaving it open for use-cases where unknown issuer claims need to be passed through.
