### ISSUE TITLE
Document known algorithm features & predicate proof support

### ISSUE THREAD

**Issue by quartzjer** [json-web-proofs/json-web-proofs#22]
* range proof
* equivalence
* blind signatures
* PoK
* set (non-)membership

etc...

**Comment by boumba100** [comment]
From what I understand, the JWP (JSON Web Proof) spec is meant to define a container format for zero knowledge proofs, like how JWS/JWT does for digital signatures. 

Since ZKPs can be used for many different things (as mentioned above), I am just wondering what type of ZKPs are in the scope of the spec. 

Is it that the spec will support all types of zero-knowledge proofs (range proofs, (non-)membership proofs, etc...) for the signed messages? Or is it just concerned about proof that data is authentic (signed by some party)? For example, a JWP could include a proof of knowledge of a signature, a proof of knowledge of the hidden messages, and proof that the hidden messages are related to the signature. With this narrower scope, proofs that are not needed to verify the authenticity of the payload would not be part of a JWP, but could instead be attached (e.g., via proof of equality) as another proof. 

 

Let me know if there are any thoughts on this. 

 

Disclaimer: We recently joined DIF, and I am trying to catch up on everything by going through the repo:) 

 

Noah

**Comment by quartzjer** [comment]
On the call today there was a question about if predicate proofs are supported.  They definitely are (any and all types), though they aren't represented directly/individually in the JWP definition and are instead expected to be an integrated part of the `proof` value.

See also #27 where we'll work on some language to describe this relationship better.

**Comment by OR13** [comment]
It might be smart to start a tentative alg registry, so we can start referring to things by unambiguous names...

If we wait too long we will have all the problems that secp256k1 has.... 

https://github.com/microsoft/VerifiableCredentials-Crypto-SDK-Typescript/blob/906128f610e14ffaf122a8b31668b0de7799c054/libs/plugin/tests/Subtle.spec.ts#L18

'K-256', 'ES256K', 'secp256k1', 'ES256K-R'...

**Comment by quartzjer** [comment]
🤔, a registry is an intriguing thought.  It would be established in the JPA draft as a place to identify different proof types.  While the details are always part of a specific JPA, I can see the benefit of unique identifiers of proof types supported by each.

This isn't quite PR-ready, but it's definitely something to re-evaluate in the near future.

**Comment by dwaite** [comment]
Has this been resolved by the recent IANA considerations section?

**Comment by selfissued** [comment]
I believe this was addressed by PR #106
