### ISSUE TITLE
Should we be separating proof signatures with ~ ?

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#35]
In the single-use JWP example, I was surprised that the signatures in the proof were simply concatenated together.  Search for "The signature for the protected header is then also appended. Using the above examples, the resulting octet string is 320 in length (5 * 64):" to see the concatenation.

The concatenation works as long as the signatures are fixed-length (which I agree is normally the case).  But we could separate the signatures by placing ~ characters between them, just as we do with payload elements.  This would be more general and provide defense in depth against bad code that uses the wrong length when parsing signatures.

This would also accommodate situations where different signatures use different algorithms and may be of different lengths.  (Will that ever occur?  Do we even know yet?)

What do people think?

**Comment by quartzjer** [comment]
For the Single Use algorithm definition I believe we'll need to add a table documenting exactly which existing JWAs are supported and what their fixed signature lengths are for each.  I don't believe any practical signature methods ever have variable length output as that would inherently violate them being uniform/indistinguishable regardless of what is signed.

The question is still valid though, since we introduce `~` as a separator for the payloads, is there utility for allowing the proof value to use it as well?

My current stance is no, as I view all of the JWP structural elements as existing to support the _application_ processing.  Every application/library using a JWP needs to understand the difference between the protected header, the individual payloads, and the opaque proof value that is passed to the relevant algorithm implementation.  All of these values can be base64url decoded by the application and treated as octet strings.

To have to pass the non-decoded proof value to the algorithm seems like an exception, and so does having the application break the proof value into parts and then pass the parts to the algorithm... the application cannot use the parts as they have no meaning to it.

So my thought is that if the algorithm needs any structure it must implement that strictly within its own layer.  All signature values have an internal structure, simple ones like XY appended for ECDSA or even much more complex ones like ( A', Abar, d, C1, e^, r2^, C2, r3^, s^, (m^[i], ..., m^[R]) ) all appended for a [BBS+ proof](https://mattrglobal.github.io/bbs-signatures-spec/#name-spkgen).  Signatures are usually kept free of structure and are a strict binary structure in order to avoid accidentally introducing an attack vector due to the structural elements or requiring a more complex parser or dependency in decoding them.

As the BBS+ example shows, the presented proof values will inevitably become internally complex, particularly as they have to encompass more variability around optional predicate proofs being included.  Even if we allowed for a `~` separator element here, it wouldn't possibly satisfy all of those needs.

**Comment by tplooker** [comment]
+1 my answer is also no, I think in general the stance for JWP should be that the signature value and any internal structure it may have should be opaque at the JWP layer (e.g treated just as a base 64 url encoded octet string) much like the internal structure of a ECDSA signature is opaque in a JWS

**Comment by quartzjer** [comment]
I'm going to close this as I believe there's consensus, we can re-open if there's additional input.
