### ISSUE TITLE
JWP does not separate the signing layer from the claims layer, like JWS and JWT do

### ISSUE THREAD

**Issue by selfissued** [json-web-proofs/json-web-proofs#4]
JWS signs a binary payload that it knows nothing about.  JWT specifies a binary payload that is an encoding of JSON claims.  The JWT spec currently specifies signing an array of payloads but *also* specifies sets of claim names for these payloads.

I'd like us to think about whether we should factor the signing part and the claims part into layered specs, analogous to JWS and JWT.  I realize that we'd still have to declare the list of payloads tied to the key in a way that didn't leak information.  And that if we layer the signing and the claims, we'd likely also have to declare the claims in a way that matched the payloads and that didn't also leak information.

Restructuring things this way may be more work, but we may end up thanking ourselves because the resulting specs will be more general.

**Comment by tmarkovski** [comment]
I think separating the signing and claims layer would definitely open up more flexibility for JWP to be used in existing proof systems that use aggregated signatures. Another approach would be adding opportunity to describe the claims layer, similar to how JWK can describe the claims, but part of the JWP in a privacy preserving way.

BBS payloads are a set of hashed messages, and those messages can either be a set of direct claims, or canonical representation of some other data structure. Some examples on potential BBS payloads:

Claims payload
```js
'{ "email":"janedoe@example.com"}'
```

N-Quad payload
```js
'_:c14n0 <http://schema.org/email> "janedoe@example.com" .'
```

JSON Pointer payload
```js
'{"/account/email": "janedoe@example.com"'
```

URI payload
```js
'https://example.com/person.json#/email'
```

Some of these payloads (Claims and URI) directly represent the signed data while N-Quads and JSON Pointer are canonical representations of the actual data. It's obvious that JWP shouldn't include the canonical form of the signed, as clients would be required to reconstruct it in order to use it, but this may be impossible, especially with N-Quads, which are used in JSON-LD signatures.

I think the JWP could allow some sort of additional indicator that described what the data is that would point to the canonicalization algorithm and include the original payload in the `payloads` field.

For example:

```js
{
  "protected": {
    "typ": "JWP",
    "alg": "BBS-BLS12381",
    "crit": [ "c14n" ],
    "c14n": "URDNA2015" // field name can be different, example only
  },
  "payloads": {
    "@context": "https://schema.org",
    "email": "janedoe@example.com"
    // JSON object can be any depth
  }
}
```

This approach will uniquely describe the final set of claims that will be signed with the specified algorithm.
When claims are used, the `c14n` field can be omitted and systems assume the format as currently described in JWP. This approach will also allow selective disclosure with BBS.

**Comment by quartzjer** [comment]
Thanks @tmarkovski, I think I follow your line of thinking.

One of the design principles of JWP is to strictly separate the static metadata that describes a payload from the actual signed payload values.  The purpose of this is to maximize unlinkability by ensuring that a JWP cannot be constructed improperly such that the location of a payload reveals identifying information.

That is the reason for having the payloads field in the JWK for any JWP, it contains the static information relating to that specific payload so that the issuer can only put those values in the same payload slots every time that key is used.

How that information is added to the JWK is definitely an area that needs to be developed, what is in the proposal right now using the "payloads" field is not scalable and really just an initial starting place.

For example, in each of your above snippets the JWK could contain something like this (I'm proposing here "layout" to identify the type of payload layout definition used):
```json
"layout":"claims",
"claims":["email",,,]
]
```
```json
"layout":"n-quads",
"n-quads":"_:c14n0 <http://schema.org/email> _:jwp0 .\r\n..."
]
```
```json
"layout":"pointers",
"pointers":["/account/email",,,]
]
```
```json
"layout":"uris",
"uris":["http://example.com/app_specific_reference",,,]
]
```

The intent here is just to ensure that the application has a single uniform definition of what the payload value in each slot represents.

As to reconstruction, I believe that should be up to the application to determine the appropriate usage and the JWP definition should support either modality.  Payload values may be reconstructed into a document (if they're available after selective disclosure) or the application may process each payload in its own individual context (such as when using predicate proofs).

**Comment by OR13** [comment]
I am not sure I am reading this correctly, but I think the ideal solution would look something like this:

```
header: { alg, layout, kid }
payload: JSON Object (not an array)
proof: { signature (s) other proof data related to alg }
```

then under `alg`:

A description of the required members of proof and requirements for payload.

For example: `BLS_BBS+JSON_POINTER` or `MERKLE+JWS+JSON_POINTER`

**Comment by quartzjer** [comment]
I think there's two things in your comment @OR13, first is your examples are all single-payload, whereas JWP is for natively supporting multiple payloads.

There's also an important perspective-change with JWP relating to what I think you're suggesting.  The payloads are intended to be used for single values, not composite structures.  I'm working on a draft update to JWP to help clarify this and we can review it at the next meeting.

This is where @dwaite's "[Mad Libs](https://github.com/json-web-proofs/json-web-proofs/issues/2#issuecomment-913865953)" analogy applies: a credential document only has the privacy sensitive values stored in the payload slots (such as the expiration timestamp is in slot 2, age value is in slot 5, email is in slot 7, etc).  The JWK that was used to issue/derive/verify for that JWP must contain the "layout" for the application to identify what values are in what slots.

Discussion and working through any confusion on this is excellent, definitely helping highlight areas to improve, thank you!

**Comment by OR13** [comment]
> JWP is for natively supporting multiple payloads.

This will cause the verifier to have to understand something of the payloads... at the very least, that each of them is independently valuable.

Are the payloads really independent?

will a verifier need to parse each payload independently?

consider a scenario where one payload is encoded with `JCS` but the other is encoded with `JSON.stringify` is this allowed?

Forcing payloads to be assembled into data models at the application layer, will prevent JWP from being capable of representing object data models natively, and will require a per object type translation for each standard object data model....

For example:

- https://w3c.github.io/vc-data-model/#credential-subject
- https://w3c.github.io/webauthn/#clientdatajson-serialization
- https://json-schema.org/understanding-json-schema/about.html
- https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#fetch-the-openid-connect-metadata-document

in each case, we start with an object, than transform it to a set of JWP payloads, then transform it back (so it conforms with the normative object definition)... 

If JWP does not define 1 way of doing this, I expect it will happen many different ways... which will harm interop, but perhaps another spec will define the way to use JWP to objects, moving normalization and aggregation outside of JWP might be strategic.

**Comment by quartzjer** [comment]
> moving normalization and aggregation outside of JWP might be strategic....

Agreed, it clicked for me last week that there can and should be a much clearer separation of concerns.

The current JWP draft needs some improvement on this front which I'm working on, reducing it to a simpler core container primitive that can be easily used with external mechanisms.

I do suspect there may be an eventual need for multiple of those external mechanisms, and they will definitely still require strong privacy considerations in order to preserve the underlying unlinkability.

**Comment by OR13** [comment]
If we do allow for `normalization` and `aggregation` outside of JWP, we can treat the message payloads as 100% opaque JSON, which would be nice... since we don't have to care about how or if they are assembled into objects that conform to existing standards.... but I suspect many folks will still want an answer to the latter, around the same time.

**Comment by quartzjer** [comment]
I'm working on a PR to reduce the scope of the JWP draft to just the signing/proving aspects, moving the payload values and any mappings out of scope: https://github.com/json-web-proofs/json-web-proofs/pull/10

We unfortunately cannot specify that the payload values are all JSON, it's essential that a proof algorithm has the ability to receive custom or raw values in order to support blinded values and/or numerical operations for range and membership proofs.

Supporting these does result in a more detailed programmatic API where each payload may have individual options passed into the algorithm, but I believe it's still the simplest abstraction that still supports the larger scope of proof capabilities.

For example, a builder pattern of the initial issuance:
Pseudocode:
```
signer = algo.signer(issuer_key, options) // options may include binding details
signer.setProtected(base64url(protected header))
signer.addPayload(payload1, options) // options may signal a blinded or numerical value
signer.addPayload(payload2)
signer.addPayload(payload3)
sig = signer.sign()
```

**Comment by OR13** [comment]
`signer.addPayload(payload1, options) ` 

doesn't this just get converted to 

`encoded proof : [ ...,  payload1WithAppliedOptions]` 

is JWP a data format or a protocol for constructing data formats?

also, might suggest changing the name before its too late.... `Json Web Proof`... implies it's a JSON based cryptographic data format...  You can encode both numbers and binary in JSON, and you can use JWS to sign binary with detached JWS `b64: false` and `crit: ['b64']`... if the output is JSON, thats good enough reason to keep the name as is... and also to define the inputs in ways that are familiar to JSON developers.

**Comment by quartzjer** [comment]
> `signer.addPayload(payload1, options) `
> 
> doesn't this just get converted to
> 
> `encoded proof : [ ..., payload1WithAppliedOptions]`

Correct, it just has to be the algorithm that applies the options.

> is JWP a data format or a protocol for constructing data formats?

It's just a data format.  Though it does create expectations for supporting protocols to convey various options.

> also, might suggest changing the name before its too late.... `Json Web Proof`... implies it's a JSON based cryptographic data format... You can encode both numbers and binary in JSON, and you can use JWS to sign binary with detached JWS `b64: false` and `crit: ['b64']`...
> 
> See https://datatracker.ietf.org/doc/html/rfc7797, you would probably want something similar if it's `critical` a verifier understands some message payloads be processed according to `options` in a specific way.

It's currently as much JSON as JWS is, and I agree we could use JSON encoding for the numbers/binary.  It'll be one of the topics I expect ongoing discussion on, as using JSON would require the algorithm implementations also parse/decode the JSON so that they can work with the raw values cryptographically.

My current preference is that they are always just opaque base64url encoded values as far as JWP is concerned, and any extra signals about their contents or algorithmic handling is out of scope.  That said, my expectation is we would also work on a companion spec that focuses on those details, very similar to the JWS/JWT relationship as suggested by @selfissued in this issue.

**Comment by OR13** [comment]
I tend to agree that small, well defined building blocks, layered correctly is a much better approach than a monolithic spec that defines everything.

I don't see a way around parsing... given the potential complexity of header values.

Does this refinement of your original example align with your thinking?

```
signer = algo.signer(issuer_key, options) // options may include binding details
signer.setProtected(base64url(JSON.stringify( header ))) // may refer to signing key and blinding details
signer.addPayload(base64url(JSON.stringify({payload: payload1, options})) // options may signal a blinded or numerical value
signer.addPayload((base64url(JSON.stringify({payload: payload2))
signer.addPayload((base64url(JSON.stringify({payload: payload3))
sig = signer.sign()
```

**Comment by quartzjer** [comment]
Your refinement is I believe in the right ballpark, it still supports the primary goal in the new PR of minimizing the scope to only what the algorithm requires in order to sign/prove.

Definitely something to discuss at today's work item call.

**Comment by OR13** [comment]
There have now been 2 concrete attempts at JWP, I am struggling to see how to make this issue actionable... I suggest closing it.

**Comment by quartzjer** [comment]
Agreed on closing it, I believe we've achieved clear separation between the core/simpler JWP and the JPT draft that introduces claims syntax.
