### ISSUE TITLE
Consider renaming "Json Proof Algorithm" and "JPA"

### ISSUE THREAD

**Issue by gabrielbauman** [json-web-proofs/json-web-proofs#54]
JPAs should probably be renamed.

- There's an initialism [clash](https://duckduckgo.com/?q=jpa&kp=1&t=newext&atb=v316-1&ia=web) with Java Persistence API (JPA), making it hard to search for
- Things like the Single Use JPA support multiple crypto "algorithms", which rapidly gets confusing: "which algorithm does this JSON Proof Algorithm use?"
- Using the JOSE "alg" key to point to something other than a cryptographic algorithm seems like a stretch and doesn't follow the principle of least surprise

I'd suggest "JSON Proof Method" or "JSON Proof Strategy".

**Comment by selfissued** [comment]
This name is intentionally parallel to JSON Web Algorithms (JWA) [RFC 7518].

Conflicts among short acronyms are inevitable.  I was upset when IBM introduced the IBM PC, because up until that point in computer circles, PC stood for Program Counter.  I got over it. ;-)

I don't see a compelling case for a name change.

**Comment by dwaite** [comment]
closing
